package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'EdFiLoadTools_BranchBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("EdFiLoadTools_BranchBuild")) {
    vcs {
        remove(RelativeId("EdFiStandard"), "+:Schemas/Bulk => Ed-Fi-Standard/Schemas/Bulk", "+:Samples/Sample XML => Ed-Fi-Standard/Samples/Sample XML")
    }
}
