package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            param("myget.feed", "https://www.myget.org/F/ed-fi/api/v3/index.json")
        }
        add {
            param("myget.apiKey.protected", "123456")
        }
        add {
            param("myget.apiKey", "%myget.apiKey.protected%")
        }
    }
}
