package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'EdFiStandard'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("EdFiStandard")) {
    val expected = GitVcsRoot({
        id("EdFiStandard")
        name = "Ed-Fi-Standard"
        url = "https://github.com/%github.organization%/Ed-Fi-Standard.git"
        branch = "%git.branch.default%"
        branchSpec = "%git.branch.specification%"
        userNameStyle = GitVcsRoot.UserNameStyle.FULL
        checkoutSubmodules = GitVcsRoot.CheckoutSubmodules.IGNORE
        serverSideAutoCRLF = true
        useMirrors = false
        authMethod = password {
            userName = "%github.username%"
            password = "%github.accessToken%"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        url = "git@github.com:Ed-Fi-Alliance-OSS/Ed-Fi-Standard.git"
        authMethod = defaultPrivateKey {
            userName = ""
        }
        param("secure:password", "")
    }

}
