# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

# This docker compose is only intended for local testing of images that have
# already been published to Docker Hub.

version: "3.8"

services:
  db-ods-minimal:
    image: edfialliance/ods-api-db-ods-minimal:pre
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TPDM_ENABLED: ${TPDM_ENABLED:-true}
    volumes:
      - vol-db-ods:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-ods
    hostname: ed-fi-db-ods
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -U ${POSTGRES_USER}"]
      start_period: "60s"
      retries: 3

  db-admin:
    image: edfialliance/ods-api-db-admin:pre
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      API_MODE: SharedInstsance
    volumes:
      - vol-db-admin:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-admin
    hostname: ed-fi-db-admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -U ${POSTGRES_USER}"]
      start_period: "60s"
      retries: 3

  api:
    image: edfialliance/ods-api-web-api:pre
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      API_MODE: sharedinstance
      ODS_POSTGRES_HOST: ed-fi-db-ods
      ADMIN_POSTGRES_HOST: db-admin
      ApiSettings__PathBase: ${ODS_VIRTUAL_NAME:-api}
      TPDM_ENABLED: ${TPDM_ENABLED:-true}
      API_HEALTHCHECK_TEST: ${API_HEALTHCHECK_TEST?Please consult env.example to set the API healthcheck test}
      NPG_POOLING_ENABLED: ${NPG_POOLING_ENABLED:-false}
      NPG_API_MAX_POOL_SIZE_ODS: ${NPG_API_MAX_POOL_SIZE_ODS}
      NPG_API_MAX_POOL_SIZE_ADMIN: ${NPG_API_MAX_POOL_SIZE_ADMIN}
      NPG_API_MAX_POOL_SIZE_SECURITY: ${NPG_API_MAX_POOL_SIZE_SECURITY}
      NPG_API_MAX_POOL_SIZE_MASTER: ${NPG_API_MAX_POOL_SIZE_MASTER}
    volumes:
      - ${LOGS_FOLDER}:/app/logs
    depends_on:
      - db-ods-minimal
      - db-admin
    restart: always
    container_name: ed-fi-ods-api
    hostname: ed-fi-ods-api
    healthcheck:
      test: ${API_HEALTHCHECK_TEST}
      start_period: "60s"
      retries: 3

  swagger:
    image: edfialliance/ods-api-swaggerui:pre
    environment:
      MINIMAL_KEY: ${MINIMAL_KEY}
      MINIMAL_SECRET: ${MINIMAL_SECRET}
      WebApiVersionUrl: https://localhost/${ODS_VIRTUAL_NAME:-api}
      PathBase: ${DOCS_VIRTUAL_NAME:-docs}
      SWAGGER_HEALTHCHECK_TEST: ${SWAGGER_HEALTHCHECK_TEST?Please consult env.example to set the SWAGGER healthcheck test}
    depends_on:
      - api
    restart: always
    container_name: ed-fi-swagger
    hostname: ed-fi-swagger
    healthcheck:
      test: ${SWAGGER_HEALTHCHECK_TEST}
      start_period: "60s"
      retries: 3

  nginx:
    build:
      context: gateway
      dockerfile: Dockerfile
    environment:
      ODS_VIRTUAL_NAME: ${ODS_VIRTUAL_NAME:-api}
      SWAGGER_VIRTUAL_NAME: ${SWAGGER_VIRTUAL_NAME:-swagger}
    ports:
      - 443:443
      - 80:80
    restart: always
    container_name: ed-fi-gateway
    hostname: nginx
    volumes:
      - ./gateway/ssl/:/ssl/
    depends_on:
      - api
      - swagger

volumes:
  vol-db-admin:
    driver: local
    name: vol-nuget-db-admin-hub
  vol-db-ods:
    driver: local
    name: vol-nuget-db-ods-minimal-hub
