# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.
 

version: '3'
services:
  db:
    container_name: ODS-PostgreSQL
    image: postgres:16.13-alpine3.23@sha256:20edbde7749f822887a1a022ad526fde0a47d6b2be9a8364433605cf65099416
    restart: always
    environment:
      # The default connection strings when using 'initdev -Engine PostgreSql' don't include a password, 
      # and, because this container it is intended to aid in local developement, postgres is configured to allow all connections
      POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      # If no port provided through an env file, default to 5432
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ed-fi-ods-dev:/var/lib/postgresql/data

volumes:
  ed-fi-ods-dev:
    driver: local

networks:
  ed-fi-ods-dev:
    external: true
