ALTER TABLE nmped.NMPEDService ADD CreatedByOwnershipTokenId SMALLINT NULL;

ALTER TABLE nmped.StudentSpecialEducationProgramAssociationSpecialEducatio_c2cadc ADD CreatedByOwnershipTokenId SMALLINT NULL;

