# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Docker Test

on:
  workflow_run:
    workflows:
      - "Publish to Azure Artifacts"
    types:
      - completed
    branches: [main]
  pull_request:
    branches: [main, 'ODS-*']
    paths:
      - "Docker/**/*"
  workflow_dispatch:

jobs:
  docker-lint:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ods-api-db-admin/alpine/pgsql
          - ods-api-db-ods-minimal/alpine/pgsql
          - ods-api-db-ods-sandbox/alpine/pgsql
          - ods-api-swaggerui/alpine
          - ods-api-web-api/alpine/mssql
          - ods-api-web-api/alpine/pgsql
          - ods-api-web-sandbox-admin/alpine/mssql
          - ods-api-web-sandbox-admin/alpine/pgsql
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        name: Run Linter on Local Dockerfile
        with:
          dockerfile: Docker/${{ matrix.image }}/Dockerfile

  docker-build:
    runs-on: ubuntu-latest
    needs: docker-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Build all of the images
        # To confirm no errors occur. The "local" one will be built by the e2e
        # testing process.
        run: |
          ./get-versions.ps1
          ./build-images.ps1
        working-directory: Docker
        shell: pwsh
