name: EdFi.Ods.Api.Sdk, TestSdk, SdkGen

on:
  repository_dispatch:
    types: [sdk-test]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  INFORMATIONAL_VERSION: "6.0"
  BUILD_INCREMENTER: "1"
  CONFIGURATION: "Release"
  CURRENT_BRANCH: ${{ GITHUB.HEAD_REF }}
  is_pull_request_branch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true
    - name: Checkout Ed-Fi-ODS-Implementation
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
      with:
          repository: bptillman/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation/
    - name: Is pull request branch exists in Ed-Fi-ODS-Implementation
      working-directory: ./Ed-Fi-ODS-Implementation/
      shell: pwsh
      run: |
          $patternName = 'refs/heads/' +  '${{ env.CURRENT_BRANCH }}'
          Write-Host "Pattern Name is " $patternName -fore GREEN
          $is_pull_request_branch = 'False'
          $is_pull_request_branch = git ls-remote --heads origin ${{ env.CURRENT_BRANCH }} | Select-String -Pattern $patternName -SimpleMatch -Quiet
          Write-Host "pull request branch is '$($is_pull_request_branch -eq $true)'" -fore GREEN
          if ($is_pull_request_branch -eq $true) {
            Write-Host "pull request branch " + ${{ env.CURRENT_BRANCH }} + "exists" -fore GREEN
            git fetch origin ${{ env.CURRENT_BRANCH }}
            git checkout ${{ env.CURRENT_BRANCH }}
          }
    - name: Checkout Ed-Fi-ODS
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS/
    - name: Is pull request branch exists in Ed-Fi-ODS
      working-directory: ./Ed-Fi-ODS/
      shell: pwsh
      run: |
          $patternName = 'refs/heads/' +  '${{ env.CURRENT_BRANCH }}'
          Write-Host "Pattern Name is " $patternName -fore GREEN
          $is_pull_request_branch = 'False'
          $is_pull_request_branch = git ls-remote --heads origin ${{ env.CURRENT_BRANCH }} | Select-String -Pattern $patternName -SimpleMatch -Quiet
          Write-Host "pull request branch is '$($is_pull_request_branch -eq $true)'" -fore GREEN
          if ($is_pull_request_branch -eq $true) {
            Write-Host "pull request branch "+ ${{ env.CURRENT_BRANCH }} + "exists" -fore GREEN
            git fetch origin ${{ env.CURRENT_BRANCH }}
            git checkout ${{ env.CURRENT_BRANCH }}
          }
    - name: Restore Nuget Packages for SdkGen
      run: |
        .\Ed-Fi-ODS-Implementation\build.githubactions.ps1 restore -Solution ./Ed-Fi-ODS/Utilities/SdkGen/EdFi.SdkGen.sln
      shell: pwsh
    - name: Build SdkGen
      run: |
        .\Ed-Fi-ODS-Implementation\build.githubactions.ps1 build -Solution ./Ed-Fi-ODS/Utilities/SdkGen/EdFi.SdkGen.sln -Configuration ${{ env.CONFIGURATION }}
      shell: pwsh
    - name: Copy SdkGen Output for Packaging
      if: success()
      run: |
        Copy-Item -Path './Ed-Fi-ODS/Utilities/SdkGen/EdFi.SdkGen.Console/bin/${{ env.CONFIGURATION }}' -Destination ./EdFi.SdkGen.Console -Recurse
    - name: Create SdkGen Output as Artifact
      if: success()
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v3.0.0
      with:
        name: EdFi.SdkGen
        path: ./EdFi.SdkGen.Console
        if-no-files-found: error
    - name: Run SdkGen Console
      if: success()
      working-directory: ./EdFi.SdkGen.Console/net6.0
      run: |
        .\EdFi.SdkGen.Console.exe -m "https://api-stage.ed-fi.org/v6.0/api/metadata" -v "5.4.0" --core-only
      shell: pwsh