name: EdFi.Installer.SwaggerUI Manually triggered build

on:
  workflow_dispatch:
  pull_request:
    branches: ['main-5x', 'b-v*-patch*','feature-*']  

env:
  INFORMATIONAL_VERSION: "5.4"
  BUILD_INCREMENTER: "1"
  AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
  AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS : '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: build
      run: |
        .\build-package.ps1 -InformationalVersion ${{env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}}  -NugetFeed ${{env.AZURE_ARTIFACT_URL}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }}
      shell: powershell
      working-directory: Scripts/NuGet/EdFi.Installer.SwaggerUI
    - name: Install-credential-handler
      run: iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"
      shell: powershell 
    - name: Publish to Azure Artifacts
      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
      run: |
        Get-ChildItem "$env:GITHUB_WORKSPACE/Scripts/NuGet/EdFi.Installer.SwaggerUI/" -Filter *.nupkg | 
        Foreach-Object {
            Write-Host "nupkg full path is " $_.FullName
            $packagePath = $_.FullName
            dotnet nuget push $packagePath --api-key ${{ env.AZURE_ARTIFACT_NUGET_KEY }} --source ${{env.AZURE_ARTIFACT_URL}} --skip-duplicate
        }
      shell: powershell       
    - name: Upload EdFi.Installer.SwaggerUI Artifacts
      if: success()
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
      with:
        name: NugetPackages.Artifacts
        path: ${{ github.workspace }}/Scripts/NuGet/EdFi.Installer.SwaggerUI/EdFi.Suite3.Installer.SwaggerUI.*.nupkg      

