# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Packages - EdFi.Ods.Minimal.Template

on:
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  INFORMATIONAL_VERSION: "6.1"
  BUILD_INCREMENTER: "1"
  CONFIGURATION: "Release"
  CURRENT_BRANCH:  ${{ GITHUB.HEAD_REF }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Ed-Fi-ODS-Implementation
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation/
    - name: Remove-EdFiDatabases
      working-directory: ./Ed-Fi-ODS/
      shell: pwsh
      run: |
          $ErrorActionPreference = 'Stop'
          $PSVersionTable
          . $env:GITHUB_WORKSPACE/Ed-Fi-ODS-Implementation/Initialize-PowershellForDevelopment.ps1
          Remove-EdFiDatabases -Force