# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

# When to Use : 
   # 1.At the time of ODS/API Major/Minor ex:6.0 Nuget Package version Deployment -Pre-release & Release package

name: Promote Packages

on:
  workflow_dispatch:
    inputs:
      promote_packages_view:
        description: 'select promote packages view for Azure Artifacts'
        required: true
        default: 'Prerelease'
        type: choice
        options:
        - Prerelease
        - Release

permissions: read-all
      
env:
  AZURE_ARTIFACT_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  AZURE_ARTIFACT_USER_NAME: ${{ secrets.AZURE_ARTIFACTS_USER_NAME }}  
  AZURE_ARTIFACTS_API_FEEDS : "https://feeds.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi"
  AZURE_ARTIFACTS_API_PACKAGING : "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi"
  HEAD_REF:  ${{ GITHUB.HEAD_REF }}
  REF_NAME:  ${{ GITHUB.REF_NAME }}
  REPOSITORY_DISPATCH_BRANCH: ${{ github.event.client_payload.branch }}  

jobs:
  FindStandardAndExtensionVersions:
    uses: Ed-Fi-Alliance-OSS/Ed-Fi-ODS/.github/workflows/Find Standard and Extension Versions.yml@874b608a0f3a14243e0035dd1222169fafcbe8d3
    with:
      calling_branch: ${{ github.head_ref || github.ref_name }}

  build:
    if: ${{ always() }}
    needs: FindStandardAndExtensionVersions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        StandardVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.StandardVersions) }}
        ExtensionVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions) }}
    name: build (Standard ${{ matrix.StandardVersion }} Extension ${{ matrix.ExtensionVersion }}) 

    steps:
    - name: Checkout Ed-Fi-ODS-Implementation
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation/
    - name: Checkout Ed-Fi-ODS
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS/
    - name: Is pull request branch exists in Ed-Fi-ODS
      working-directory: ./Ed-Fi-ODS-Implementation/
      shell: pwsh
      run: |
        .\build.githubactions.ps1 CheckoutBranch -RelativeRepoPath "../Ed-Fi-ODS"          
    - name: Update Standard ${{ matrix.StandardVersion }} and Extension ${{ matrix.ExtensionVersion }} in configuration.packages.json
      working-directory: ./Ed-Fi-ODS-Implementation
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Import-Module "./logistics/scripts/modules/settings/settings-management.psm1"
        $filePath = "./configuration.packages.json"
        $config = Get-Content $filePath | ConvertFrom-Json
        $StandardVersion = '${{ matrix.StandardVersion }}'
        $ExtensionVersion = '${{ matrix.ExtensionVersion }}'
        Write-Host("StandardVersion value is $StandardVersion")
        Write-Host("ExtensionVersion value is $ExtensionVersion")
        
        foreach ($package in  $config.packages.psobject.properties) 
        {
            $selectedPackageName = $config.packages.$($package.Name).PackageName
            $packageName = $config.packages.$($package.Name).PackageName.Replace("{StandardVersion}",$StandardVersion).Replace("{ExtensionVersion}",$ExtensionVersion)

            if ($selectedPackageName -ne $packageName)
            {
                $config.packages.$($package.Name).PackageName  = $packageName
                Write-Host("$selectedPackageName Package replaced with  $packageName")
            }
        }
        $config | ConvertTo-Json | Format-Json | Out-File -FilePath $filePath -Encoding UTF8 
       
    - name: Promote Packages
      working-directory: ./Ed-Fi-ODS-Implementation
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        ./logistics/scripts/activities/build/promote-packages.ps1 -FeedsURL "${{ env.AZURE_ARTIFACTS_API_FEEDS }}" -PackagesURL "${{ env.AZURE_ARTIFACTS_API_PACKAGING }}" -Username "${{ env.AZURE_ARTIFACT_USER_NAME }}"  -Password  (ConvertTo-SecureString -String "${{ env.AZURE_ARTIFACT_PERSONAL_ACCESS_TOKEN }}" -AsPlainText -Force) -View "${{ inputs.promote_packages_view }}" -StandardVersion ${{ matrix.StandardVersion }}
 
