# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Promote Packages

on:
  pull_request:
    branches:
      - main      

env:
  AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
  AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS : '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
  AZURE_ARTIFACTS_API_FEEDS : "https://feeds.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi"
  AZURE_ARTIFACTS_API_PACKAGING : "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi"
  AZURE_ARTIFACTS_EDFI_BUILD_AGENT_USERNAME : "EdFiBuildAgent@chrismoffattedfi.onmicrosoft.com"
  AZURE_ARTIFACTS_EDFI_BUILD_AGENT_ACCESSTOKEN : "******"
  SCRIPT_PROMOTE_PACKAGES_VIEW : "Prerelease"
  SCRIPT_PROMOTE_PACKAGES.WHATIF :  ${{ true }}

jobs:
  build:

    runs-on: windows-latest
 
    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true
    - name: Checkout Ed-Fi-ODS-Implementation
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation/
    - name: Checkout Ed-Fi-ODS
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS/
    - name: Promote Packages
      working-directory: ./Ed-Fi-ODS-Implementation
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'

        $parameters = @{
          FeedsURL    = "${{ env.AZURE_ARTIFACTS_API_FEEDS }}"
          PackagesURL = "${{ env.AZURE_ARTIFACTS_API_PACKAGING }}"  
          Username    = "${{ env.AZURE_ARTIFACTS_EDFI_BUILD_AGENT_USERNAME }}"  
          Password    = (ConvertTo-SecureString -String "${{ env.AZURE_ARTIFACT_NUGET_KEY }}" -AsPlainText -Force)
          View        = "${{ env.SCRIPT_PROMOTE_PACKAGES_VIEW }}"
          WhatIf      = $true
        }
         ./logistics/scripts/activities/build/promote-packages.ps1 -FeedsURL "${{ env.AZURE_ARTIFACTS_API_FEEDS }}" -PackagesURL "${{ env.AZURE_ARTIFACTS_API_PACKAGING }}" -Username "${{ env.AZURE_ARTIFACTS_EDFI_BUILD_AGENT_USERNAME }}"     -Password  (ConvertTo-SecureString -String "${{ env.AZURE_ARTIFACTS_EDFI_BUILD_AGENT_ACCESSTOKEN }}" -AsPlainText -Force) -View "${{ env.SCRIPT_PROMOTE_PACKAGES_VIEW }}"
