# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Publish to Docker Hub
on:
  pull_request:
   branches: [b-v*-patch*]
  workflow_run:
    workflows:
      - "Docker Test"
    types:
      - completed
    branches:
      - b-v*-patch*
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package Version'
        required: true
        default: "7.1"
        type: string

env:
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
  CURRENT_STANDARD_VERSION: "5.0.0"
  PACKAGE_VERSION: "7.1"
  EVENT_NAME: ${{ GITHUB.EVENT_NAME }}
  EVENT_ACTION: ${{ GITHUB.EVENT.ACTION }}
  HEAD_REF:  ${{ GITHUB.HEAD_REF }}
  REF_NAME:  ${{ GITHUB.REF_NAME }}
  REPOSITORY_DISPATCH_BRANCH: ${{ github.event.client_payload.branch }}  

jobs:

  FindStandardAndExtensionVersions:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    outputs:
      StandardVersions: ${{ steps.Set_StandardVersions.outputs.StandardVersions }}
      ExtensionVersions: ${{ steps.Set_ExtensionVersions.outputs.ExtensionVersions }}
    steps:
    
      - name: Checkout Ed-Fi-ODS-Implementation
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
                repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
                path: Ed-Fi-ODS-Implementation/
                ref: ${{ github.ref_name || github.head_ref }}
      - name: Checkout Ed-Fi-ODS
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS/
          ref: ${{ github.ref_name || github.head_ref }}
      - name: Checkout Ed-Fi-Extensions
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
            repository: Ed-Fi-Alliance-OSS/Ed-Fi-Extensions
            path: Ed-Fi-Extensions/

      - name: Is pull request branch exists in Ed-Fi-Extensions
        working-directory: ./Ed-Fi-ODS-Implementation/
        shell: pwsh
        run: |
          .\build.githubactions.ps1 CheckoutBranch -RelativeRepoPath "../Ed-Fi-Extensions"

      - name: Is pull request branch exists in Ed-Fi-ODS
        working-directory: ./Ed-Fi-ODS-Implementation/
        shell: pwsh
        run: |
            .\build.githubactions.ps1 CheckoutBranch -RelativeRepoPath "../Ed-Fi-ODS"          

      - name: Set StandardVersions
        id: Set_StandardVersions
        working-directory: ./Ed-Fi-ODS/
        run: |
          $output = .\build.githubactions.ps1 StandardVersions -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj"
          echo "StandardVersions=$output" >> $env:GITHUB_OUTPUT
          Write-host "StandardVersions is  $output"
        shell: pwsh

      - name: Set ExtensionVersions
        id: Set_ExtensionVersions
        working-directory: ./Ed-Fi-Extensions/
        run: |
          $output = .\build.githubactions.ps1 ExtensionVersions -ProjectFile "$env:GITHUB_WORKSPACE/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM/EdFi.Ods.Extensions.TPDM.csproj"
          echo "ExtensionVersions=$output" >> $env:GITHUB_OUTPUT
          Write-host "ExtensionVersions is  $output"
        shell: pwsh

  docker-publish:
    if: (needs.FindStandardAndExtensionVersions.outputs.StandardVersions != '' &&
        needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions != '')
    needs: FindStandardAndExtensionVersions
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        StandardVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.StandardVersions) }}
        ExtensionVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions) }}
    name: Publish to Docker Hub (Standard ${{ matrix.StandardVersion }} Extension ${{ matrix.ExtensionVersion }})
    steps:
      - name: Check for Docker Hub Token
        if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.DOCKER_HUB_TOKEN == '' }}
        run: | 
          echo "::error::Missing Docker Hub Token"
          exit 1   
      - name: Exit success if Docker Hub Token is missing in forked repository
        if: ${{ env.DOCKER_HUB_TOKEN == '' }}
        run: |
          echo "Skipping Publish"           
      - name: Wait 20s for Azure Artifacts caching
        run: sleep 20

      - name: Checkout Repository
        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Log in to Docker Hub
        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d  # v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
        run: |
          # Note: all images will receive the same version number for this Docker release
          if (($env:EVENT_NAME -eq "release" -and $env:EVENT_ACTION -eq "published") -or ($env:EVENT_NAME -eq "workflow_dispatch")) {

            $package_version="${{ env.PACKAGE_VERSION }}"
            if ($env:EVENT_NAME -eq "workflow_dispatch") {
              $package_version="${{ inputs.package_version }}"
            }

            ./get-versions.ps1 -PackageVersion $package_version -StandardVersion ${{ matrix.StandardVersion }} -ExtensionVersion ${{ matrix.ExtensionVersion }}
            ./build-images.ps1 -Push -PackageVersion $package_version -Patch ${{ github.run_number }}
            Write-Host "This step is triggered manually or by a published release."
          }
          else
          {
            ./get-versions.ps1 -PackageVersion ${{ env.PACKAGE_VERSION }} -StandardVersion ${{ matrix.StandardVersion }} -ExtensionVersion ${{ matrix.ExtensionVersion }} -PreRelease
            ./build-images.ps1 -Push -PackageVersion ${{ env.PACKAGE_VERSION }} -Patch ${{ github.run_number }} -PreRelease
            Write-Host "This is for ${{ env.PACKAGE_VERSION }} Pre Release."
          }
        working-directory: Docker
        shell: pwsh
